### ISSUE TITLE
Calculated breathing seconds should count to minutes

### ISSUE THREAD

**Issue by mdwalters** [MeoMix/symbiants#24]
Just a small suggestion, I think the calculated breathing seconds should be shown as `2 minutes and 8 seconds` instead of just `128 seconds` in this screenshot, for example.

![image](https://github.com/MeoMix/symbiants/assets/67456566/9b77dc74-6832-4b64-aeba-f518a7157fdf)

**Comment by MeoMix** [comment]
https://github.com/MeoMix/symbiants/commit/dc6564d9e50be7a8d4831bb8c35977513aafe1d5

🎉 

Thanks for the suggestion
